### PR TITLE
Fix Warrior Enraged Regeneration spell

### PR DESCRIPTION
**Pull request by AGandrup**
**Changes proposed**:

- Warriors will no longer be able to gain Enrage effects while Enraged Regeneration is active, as stated in the Enraged Regeneration tooltip.
- Enraged Regeneration will no longer be able to be activated from Vengeance, as stated in the Vengeance tooltip.

**Tests performed**:

- Tested in game, works as intended.

**Known issues and TODO list**:

- TODO/Suggestion: Perhaps it would make sense to add more unit states in relation to spell mechanics, for example UNIT_STATE_ENRAGED, so that in a case like this we could use the CONDITION_UNIT_STATE to check if unit is enraged, instead of having to go through all possible spells with enrage effects etc.

### CODE REVIEW

**Comment by Ovahlord** [comment]
You will be surprised but there already is AURA_STATE_ENRAGE which is the requirement for enrage based spells to be casted. So checking for the aura state is the way to go here. Also usually stuff like this belongs into spell scripts

**Comment by AGandrup** [comment]
Oh okay, excellent. I will have to look into this some more then.
Is AURA_STATE_ENRAGE something that can be used for conditions as well or is that only related to spell scripts?

**Comment by Ovahlord** [comment]
I's only available for spell scripts and that's fine because stuff like this usually belongs into spell scripts at least for class scripts

**Comment by AGandrup** [comment]
Right, that makes sense. Was just wondering

**Comment by Ovahlord** [comment]
So from what I read on the webs, Enraged Regeneration does not block the cast of these effects, instead it just renders you immune to any other spell that uses MECHANIC_ENRAGE

**Comment by AGandrup** [comment]
So what that means is, if Enraged Regeneration is active then Berserker Rage and Deathwish can still be used but wont do anything? So you would basically just waste your cooldown and rage on nothing? Seems odd if thats the case...

**Comment by Ovahlord** [comment]
Looks like it. The only difference between the WotLK and Cata version is that the Cataclysm version no longer consumes enrage effects but otherwise, their functionality is identical and based on that, the WotLK also applied the enrage immunity which, weirdly enough, is no longer in the Cataclysm dbc entry for it.

**Comment by Ovahlord** [comment]
f94ce7954377e4486dae2c2603c0898dc12b2a49  there we go

**Comment by AGandrup** [comment]
> [f94ce79](https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/f94ce7954377e4486dae2c2603c0898dc12b2a49) there we go

Alright, going with that solution then. Awesome 👍

**Pull request closed without merging**
