### PR TITLE
[W.I.P] Add Sinestra encounter

### LINKED ISSUE #19: Sinestra - Implement encounter

### PR DESCRIPTION
**Pull request by Dreaxxx**
**Changes proposed**:

- Try implement sinestra encounter in the project

**Issues addressed**: Fixes #19 

**Tests performed**: Build passed after rework , but no effect in game

**Known issues and TODO list**:

- After modify of the scriptname  for Sinestra , Whelp and the 2 others adds, remove unit flag IMMUNE player , nothing append in game
- If a real dev can check the code and tell me what is wrong with it , i'll help more ! 
- Sorry i'm begginer in C++ and with trinitycore

### CODE REVIEW

**Comment by funjoker** [comment]
Use rebase instead of merges please

**Comment by Dreaxxx** [comment]
> Use rebase instead of merges please

Ah yes sorry , next time will do :)

**Comment by Dreaxxx** [comment]
If someone find how to resolve the segmentation fault during phase 2 in the UpdateAI, that's the only wrong thing who block me :/

**Comment by Ovahlord** [comment]
So the first thing you should do when you write scripts is: do it yourself from scratch. This code is based on several sources who are known to be wrong and hacky so if you want to learn as fast as possible: code it yourself and use modern codes as reference to get a feeling for the coding standards.

**Comment by funjoker** [comment]
For example:
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/95bb620355bc41af758efa16fc8a807bfbd07efc

**Comment by Dreaxxx** [comment]
Okay, I'll try to make some scripts from scratch ^^
So I close the PR?

**Pull request closed without merging**
