### PR TITLE
Core/Players: Several gold handling improvements

### PR DESCRIPTION
**Pull request by roc13x**
**Changes proposed**:

Updated the following systems to support large (64bit) gold numbers:
- Auction House
- Mail
- Commands
- Guild bank withdraw limits
- Guild Bank eventlog
- Vendor

Fixed some vendor checks for when BuyCount > 1.
Tweaked some checks for available gold space.

**Tests performed**: Built and tested ingame

### CODE REVIEW

**Comment by Ovahlord** [comment]
Hey there. Any known issues to test or to take into consideration?

**Comment by roc13x** [comment]
Hey. Not sure if there’s any open issues on the tracker about it, but if you try to use the above features (AH, mail COD, etc) with large gold amounts (over 430k) it won’t work properly as the values get saved and loaded from DB as uint32, capping the amount at 430k.
This PR simply converts most money handling code to consistently use int64, to support amounts over 430k

**Comment by Ovahlord** [comment]
aight. any prending changes then or is it ready?

**Comment by roc13x** [comment]
All ready to go :) squashed the commits into one

**Comment by Ovahlord** [comment]
Thanks for your contributen then. Nice to see some familiar faces arround here that know what to do

**Pull request merged**
