### PR TITLE
Core/PacketIO: convert all authentication related packets to packet c…

### PR DESCRIPTION
**Pull request by Ghaster**
…lass

Quite a few changes this time around:
- Converted `CMSG_PING`, `SMSG_PONG`, `SMSG_AUTH_CHALLENGE` and `SMSG_AUTH_RESPONSE` to packet class.
- Renamed `SMSG_REDIRECT_CLIENT` to `SMSG_CONNECT_TO`.
- Implemented `CMSG_CONNECT_TO_FAILED` and `SMSG_CHARACTER_LOGIN_FAILED`, which allows up to 5 `SMSG_CONNECT_TO` reconnects.
- Implemented `SMSG_WAIT_QUEUE_UPDATE` and `SMSG_WAIT_QUEUE_FINISH`. Fixes queue display when server is full.
- Replaced some arrays in `AuthenticationPackets.h` with modern C++ arrays.
- Replaced `Expansion()` with `GetAccountExpansion()` and `GetExpansion()` (functionality should be self-explanatory).
- Fixed functionality of `LogUnprocessedTail()` for packet class.
- Purged duplicate `AuthSession` struct in `WorldSocket.cpp`.

All enums/packet structures have been verified aswell.

### CODE REVIEW

**Comment by Ovahlord** [comment]
Are the enum values in LoginFailureReason taken from master or where did you get the validated data from for 434?

**Comment by Ghaster** [comment]
Those are taken from the 4.3.4 client (relevant handler from IDA: https://gist.github.com/Ghaster/19d2ea254a69c9b3e70864b375f024c4)

**Comment by Ovahlord** [comment]
aight. what tests did you perform in advance and are there any complications to take into consideration?

**Comment by Ghaster** [comment]
Tested by simply logging into the world and forcing the server to show a queue by setting the playerlimit to 1.
The only thing I haven't tested is `CMSG_CONNECT_TO_FAILED`, as I can't reproduce an instance where it would send it. However the handling of that packet hasn't changed between cata and WoD 6.0.x and the packet structure used is from 4.3.4, so it should work.
Also `LogUnprocessedTail()` is apparently still not working. It is getting called, but the output of `packet->wpos()` always returning 0, no matter if the packet is fully read or not.

**Comment by Ovahlord** [comment]
well, if you would be so kind and resolve the merge conflicts I gonna merge it and see if I can find the source of the problem regarding LogUnprocessedTail

**Comment by Ghaster** [comment]
Done 👍 squashed the commits aswell.

**Pull request merged**
