### PR TITLE
Core/Spells: Implement alternative visuals for dynamic objects

### PR DESCRIPTION
**Pull request by Warpten**
Fixes ring of frost showing up as red when it's owned by an opponent. Same story for smoke bomb and whatever else.

Side opinion: Copy-pasting `Object::BuildValuesUpdate` is ugly, the varied handling should happen on the `operator <<` call (for example with a virtual that returns the proper value based on the seer). But it's also done by `GameObject`, so whatever.

### CODE REVIEW

**Comment by Ovahlord** [comment]
Hold on a second. Ring of Frost and that holy priest bubble are npcs with simple auras. I guess this applies more to smoke bomb, death and decay etc.

**Comment by Warpten** [comment]
Right. 34997 is the needed display id for ring of frost, but this commit is still kind of needed

**Comment by Ovahlord** [comment]
I will do final checks and push the shiny button when I am back home in about a week.

**Comment by Warpten** [comment]
I hate inplicit casts and so should you

:p

**Pull request merged**
