### PR TITLE
Fix Rogue spell Redirect

### LINKED ISSUE #207: [SPELL/ROGUE] Redirect
**Current behaviour:**

Does nothing.

**Expected behaviour:**

Read tooltip.

**Steps to reproduce the problem:**

1. Stack combo points on one target
2. Target a different target and cast Redirect

**TC rev. hash/commit:** 

5c0febcfb38828a28da9edd27900a85e052cc738

**TDB version:** 

TDB 434.20091

**Operating system:** 

Win10 64

### PR DESCRIPTION
**Pull request by AGandrup**
**Changes proposed**:

- Can no longer be used without any existing combo points.
- Can no longer be used on target with combo points already.
- Will now properly transfer combo points to a new target.
- Bandit's Guile + Insights will now be transfered along with combo points as intended.

**Issues addressed**: 
- Fixes #207 

**Tests performed**: 
- Builds.
- Works as intended ingame.

**Known issues and TODO list**:

~TODO: Fix transfering bandits guile. This requires some rework of AuraScript ```spell_rog_bandits_guile``` as this will currently always clear insight buffs when hitting a new target.~

### CODE REVIEW

**Comment by Ovahlord** [comment]
I'm not a fan of this script. SetAmount is usually never being used so this implies that what you are doing here is very likely a hack. The Bandit's guile part can be solved differently by accessing the aurascript of the rogue and using a public method to change the proc guid.

**Comment by AGandrup** [comment]
Right, I get what you are saying - that would probably be cleaner too. I'll figure it out.

**Comment by AGandrup** [comment]
Actually, I'm a bit confused. Can I just move an aura from one unit to another by swapping a GUID? I don't need to specifically say "add new aura to new target", "remove old aura from previous target"?

**Comment by Ovahlord** [comment]
No, but you can access the player's proc aurascript and alter the previous target guid to the new one that you redirect to so the proc just keeps going as nothing has changed.

**Pull request closed without merging**
