### PR TITLE
Fixed build for newer OpenSSL and MariaDB

### PR DESCRIPTION
**Pull request by danielsreichenbach**
**Changes proposed**:

- add support for building against OpenSSL 3.0
- replaced mentions of authserver with bnetserver
- updated list of external dependencies with correct information
- fixed a warning in connection patcher for Linux

**Issues addressed**: None

**Tests performed**: (Does it build, tested in-game, etc)

- [X] Builds
- [X] Can connect and play

**Known issues and TODO list**: None

### CODE REVIEW

**Comment by FuzzyWuggzy** [comment]
Thank you for this, it helped with the OpenSSL incompatibility, but it still won't build and returns this error:

```
[ 83%] Building CXX object src/server/game/CMakeFiles/game.dir/Maps/MapReference.cpp.o
In file included from /mnt/[UUID]/TrinityCore/src/server/game/Handlers/TicketHandler.cpp:29:
/mnt/[UUID]/TrinityCore/src/server/game/Server/Packets/TicketPackets.h:71:43: error: declaration of ‘TaggedPosition<Position::XYZ> WorldPackets::Ticket::SupportTicketHeader::Position’ changes meaning of ‘Position’ [-fpermissive]
   71 |             TaggedPosition<Position::XYZ> Position;
      |                                           ^~~~~~~~
In file included from /mnt/[UUID]/TrinityCore/src/server/game/Entities/Object/MovementInfo.h:22,
                 from /mnt/[UUID]/TrinityCore/src/server/game/Entities/Object/Object.h:27,
                 from /mnt/[UUID]/TrinityCore/src/server/game/Entities/Unit/Unit.h:21,
                 from /mnt/[UUID]/TrinityCore/src/server/game/Entities/Creature/Creature.h:21,
                 from /mnt/[UUID]/TrinityCore/src/server/game/PrecompiledHeaders/gamePCH.h:20,
                 from /mnt/[UUID]/TrinityCore/build/src/server/game/CMakeFiles/game.dir/cmake_pch.hxx:5,
                 from <command-line>:
/mnt/[UUID]/TrinityCore/src/server/game/Entities/Object/Position.h:27:20: note: ‘Position’ declared here as ‘struct Position’
   27 | struct TC_GAME_API Position
      |                    ^~~~~~~~
make[2]: *** [src/server/game/CMakeFiles/game.dir/build.make:2477: src/server/game/CMakeFiles/game.dir/Handlers/TicketHandler.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1241: src/server/game/CMakeFiles/game.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

```

I'm not sure this is related to your PR, I can't build the master branch without downgrading OpenSSL system-wide. It built successfully for you and no commits have been made in two weeks so I can't say what the issue is.

Thank you again

Kind regards

**Comment by Vecel91** [comment]
Successfully built on Ubuntu 22.04

**Comment by Ovahlord** [comment]
Mind to rebase this PR with the current head branch pls?

**Comment by danielsreichenbach** [comment]
> Mind to rebase this PR with the current head branch pls?

Not at all, just pushed a rebased version of it.

**Comment by Ovahlord** [comment]
so apparently this PR has not been tested because I just did so and the bnetserver crashes right away when logging. so there are bits and pieces missing somewhere

**Comment by danielsreichenbach** [comment]
> so apparently this PR has not been tested because I just did so and the bnetserver crashes right away when logging. so there are bits and pieces missing somewhere. Apparently the ARC4 part is missing quite a few refactors which needs to be cherrypicked first.

Am running this for almost two months on a Ubuntu Linux machine, and did not get crashes there. Can check if you can tell me what settings you are using.

**Comment by Ovahlord** [comment]
I'm running it on Windows 11 using openssl 3.1. So if Linux runs fine, it's likely a missing compatability fix

**Comment by Ovahlord** [comment]
https://gist.github.com/Ovahlord/d150ef591fea528f1f1dbcd8711850b7  here's a crashlog if that helps you investigating

**Comment by Ovahlord** [comment]
well, based on my investigations, you forgot the entirety of HmacHash which is still using deprecated openssl methods and thus causing ARC4 to fetch a nullptr

**Comment by Shauren** [comment]
I have not looked at the code at all but any crashing that happens on windows but not on linux is because of a user error not copying legacy.dll in addition to the usual openssl dlls from install dir to server dir

**Comment by Ovahlord** [comment]
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/a7527a8698e7c7ee5ca0c1f18f31d4e63400fd9d

**Pull request closed without merging**
