### PR TITLE
Fix chase movement

### LINKED ISSUE #345: Non-flying NPCs walk in air and through objects and terrain.
**Description:**

Non-flying NPCs can walk in the air and through objects/terrain. This happens when the NPC is chasing its target thus generating a path to its target. For the most part, this bug occurs when the NPC cannot see its target (Out of Line of Sight).

**Current behaviour:**

Non-flying NPCs can generate a path to the target that it is chasing, regardless of the path being valid or not, causing it to walk in the air and walk through objects/terrain.

**Expected behaviour:**

If no valid path is available the NPC should stand still and eventually reset.

**Steps to reproduce the problem:**

It can be a bit difficult to reproduce as it depends on where you are standing. But anyway:
1. Have flying enabled. `.gm fly on` 
2. Aggro an NPC.
3. Fly ontop of a building, wall or any area that are unreachable without flying - though you must still be in aggro range to keep the NPC chasing you.
4. When you find a spot, keep adjusting your position on that area. Watch the behavior of the NPC. If you notice it start walking in the air, then stand still and you should see it walk all the way up to you.

**TC rev. hash/commit:** 

TrinityCore rev. c9d9066cfa26+ 2022-04-02 17:52:10 +0200 (dev-blizzlike branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:** 

TDB 434.22011

**Operating system:**

Windows 10

**Notes:**

I have somewhat solved the problem though I am not happy with solution which is why I haven't made a PR.
I have tried quite a lot things and what seems to work the best so far, is just checking the difference between the NPCs end position and its current position and see if the end Z position is higher than the current Z position and if the end X and Y positions are too close to the current X and Y positions. Unfortunatly, doing it this way kinda breaks path finding in a way so that NPCs wont walk to you if you are right above them even though there is a valid path leading up to you.

A proper solution (I think) is to "look one step in the future" - So basically check if the Z position of the NPCs next step is higher than the next steps' FloorZ position. If so, then we know that the NPC is trying to walk in the air and we can just simply prevent it from moving. Unfortunatly I haven't really found my way to do this yet, which is why I am now opening an issue.

### PR DESCRIPTION
**Pull request by AGandrup**
**Changes proposed**:

- Added method for checking if next step of chasing unit is valid

**Issues addressed**: 

- Fixes #345 

**Tests performed**: 

- Builds
- Tested in game, everything seems to work exactly as inteded i.e. chasing targets will no longer walk in air nor clip through terrain and objects. Chasing targets can still reach its target that are on higher ground if there is a valid path leading to it.

**Note**:

- I went with 5 yards difference as I think that sounds reasonable, but it can be up for discussion whether this should be increased or decreased.

### CODE REVIEW

**Comment by Ovahlord** [comment]
This is a hack. For such cases we have to check if the path generation result has returned a shortcut because that's when recast tells us that a regular generation was not possible.

**Comment by AGandrup** [comment]
Meh, guess I'll go back to the drawing board then. I was so confident with this solution though. Anyway, can you point out to me where I should start looking? I am not sure where this recast is happening.

**Comment by Ovahlord** [comment]
https://gist.github.com/Ovahlord/c36b92871f2062efb47536ddc57e8c0d try that

**Comment by AGandrup** [comment]
> https://gist.github.com/Ovahlord/c36b92871f2062efb47536ddc57e8c0d try that

This does not solve the problem

**Comment by Ovahlord** [comment]
In that case it's a problem with Recast itself and cannot be solved via movement generator.

**Comment by AGandrup** [comment]
Hmm okay, I'll see what I can do.

**Comment by AGandrup** [comment]
I'll let it be up for someone else to solve this for now. I don't really have enough knowledge yet to wrap my head around how Recast works. So I am just going to close this PR.

**Pull request closed without merging**
