### PR TITLE
Build on Linux

### PR DESCRIPTION
**Pull request by pangolp**
### Changes proposed

- These changes were taken from the current TrinityCore branch, since when I tried to compile on Linux, it failed. Researching and reviewing the files, I found these differences, which I tested and with them I managed to compile in Ubuntu 21.10

### Issues addressed
- Closes

### Tests performed
- Windows 10.
- Ubuntu 21.10
- Arch Linux (by [kaiyazeera](https://github.com/kaiyazeera))

### CODE REVIEW

**Comment by kaiyazeera** [comment]
you can add Arch Linux (since it's a rolling release: date today) to the list of tests performed.

**Comment by pangolp** [comment]
> you can add Arch Linux (since it's a rolling release: date today) to the list of tests performed.

Thank you, I will add it. But I think I'm going to close the PR, because it seems that the community is not interested in the contribution.

**Comment by kaiyazeera** [comment]
You might consider leaving it open because it still helps users manually patching the core source (even though in my case, I got stuck with the mmaps afterwards, but I do not see how your code would interfere with that). I for my part really appreciate the contribution.

**Comment by pangolp** [comment]
> You might consider leaving it open because it still helps users manually patching the core source (even though in my case, I got stuck with the mmaps afterwards, but I do not see how your code would interfere with that). I for my part really appreciate the contribution.

We will create another community, don't worry, and of course, if you want, you are invited. Contact me by discord, so you can have more information about it. Stevej#5879. By the way, I do not speak English. I use a translator.

**Pull request closed without merging**
