### PR TITLE
Trainer Gossip Fixes

### PR DESCRIPTION
**Pull request by acidmanifesto**
This is from a jr beginner dev @dsikiba thats apart of our cata community opensource project that is just beginning that is based on the CPP latest revisions.
Myself and @jinnaix assisted with the formatting of the SQL.

***Issue:***
-Select trainers would not open gossip windows when you click on them .
-Select trainers when the windows opened they would not do anything when you selected a option.

**Changes proposed**:

***What this fixes:***
This corrects both issues with the following trainers
Alliance
-- https://www.wowhead.com/npc=43455/saripal-smolderbrew Ironforge Warlock Trainer
-- https://www.wowhead.com/npc=43006/rhyanda Darnassus Mage Trainer
-- https://www.wowhead.com/npc=42331/bipsi-frostflinger New Tinkerton Mage Trainer
-- https://www.wowhead.com/npc=37121/teegli-merrowith Ironforge Mage Trainer
-- https://www.wowhead.com/npc=37115/teo-hammerstorm Ironforge Shaman Trainer
-- https://www.wowhead.com/npc=42323/doc-cogspin New Tinkerton Priest Trainer
-- https://www.wowhead.com/npc=42366/kelsey-steelspark New Tinkerton Rogue Trainer

Horde
-- https://www.wowhead.com/npc=15279/julia-sunstriker Sunstrider Isle Mage Trainer
-- https://www.wowhead.com/npc=15284/matron-arena Sunstrider Isle Priest Trainer
-- https://www.wowhead.com/npc=15280/jesthenis-sunstriker Sunstrider Isle Paladin Trainer
-- https://www.wowhead.com/npc=42618/voldreka Echo Islands Warlock Trainer
-- https://www.wowhead.com/npc=15285/pathstalker-kariel Sunstrider Isle Rogue Trainer
-- https://www.wowhead.com/npc=38244/legati Echo Isles Rogue Trainer
-- https://www.wowhead.com/npc=39214/karranisha Valley of Trials Hunter Trainer
-- https://www.wowhead.com/npc=15513/ranger-sallina Sunstrider Isle Hunter Trainer
-- https://www.wowhead.com/npc=15283/summoner-telilarien Sunstrider Isle Warlock Trainer

**Tests performed**:
Verified each individual Trainer that is in the sql and verifies they now work as intended.

**Known issues and TODO list**:
Audit the rest of the trainers in CPP to see if there is any more issues with opening gossip windows or nothing happening when selecting gossip options.

### CODE REVIEW

**Comment by Ovahlord** [comment]
So first of all, the sql file does not follow formatting standards.  Every query command is written in upper case and column names must be specified.

Next, the gossip menu option entries have a verified build of 15600 which is a non-existing client build so these entries are not sniffed so they are most likely hacky. VerifiedBuild is only being used by packet parser sql outputs and must not be set by hand.

**Comment by dsikiba** [comment]
the 15600 was just a number i put in to keep track of my edits. i was told the number didnt have a effect on the server running so i played with it and these arnt sniffed i have no idea where to begin with that. my goal for this was to restore functionality of the trainers. i think i did a ok job of making this one for my first sql fix ever. i didnt think you would accept it i just wanted to show my work as a thank you for the source.

**Comment by funjoker** [comment]
```
VerifiedBuild
This field is used by the TrinityDB Team to determine whether a template has been verified from WDB files.
If value is 0 then it has not been parsed yet.
If value is above 0 then it has been parsed with WDB files from that specific client build.
If value is -1 then it is just a place holder until proper data are found on WDBs.
If value is -Client Build then it was parsed with WDB files from that specific client build and manually edited later for some special necessity.

```

**Comment by acidmanifesto** [comment]
> ```
> VerifiedBuild
> This field is used by the TrinityDB Team to determine whether a template has been verified from WDB files.
> If value is 0 then it has not been parsed yet.
> If value is above 0 then it has been parsed with WDB files from that specific client build.
> If value is -1 then it is just a place holder until proper data are found on WDBs.
> If value is -Client Build then it was parsed with WDB files from that specific client build and manually edited later for some special necessity.
> ```

Thats actually good bit to know.

**Pull request closed without merging**
