### PR TITLE
Core/Spell: Warlock's Demon Soul spell Ids correction

### PR DESCRIPTION
**Pull request by Nyr97**
**Changes proposed**:

- [x] Warlock Demon Soul's aura ID for Felhunter, Felguard and Voidwalker fixed.
- [x] FollowMovementGenerator will respect the creature's HoverHeight when it launches movement and aligns to its target.
- [x] Creature's HoverHeight is kept when using ChaseMovementGenerator.
**Issues addressed**: 

- When using Demon Soul while having a Felguard, Succubus or Voidwalker as pet, the warlock wouldn't get its proper buff due to a misspelling of aura IDs.

- A creature's HoverHeight should be kept while using FollowMovementGenerator either when launching movement or aligning to its target.

**Tests performed**: 

It builds, tested in game.

**Known issues and TODO list**:

### CODE REVIEW

**Comment by Ovahlord** [comment]
Please add a few more details why you have added the hover changes to the follow movement generator because the path generation automatically applies hover offsets when a unit is actually hovering.

**Comment by Nyr97** [comment]
As far as I tested and before applying this change, setting any hover height to a creature’s template which is then made to follow a player through a charm effect won’t be taken into account after reaching the destination of a launch movement or aligning to a player. In fact, you can see a creature clips through the ground constantly whether you set the creature's movement as Ground, Flying or both to 1. The creature also clips through the ground when it reaches its destination or aligns up to the player when its movement ground is set to 2. Here's a video of the current state of the system prior to my changes: https://youtu.be/uF0T9_39D1c

I haven’t seen any code in the FollowMovementGenerator that really fixes this feature and the change proposed fixes this behaviour. Here's a video of the change: https://youtu.be/YTDCAXQ92aU

**Comment by Ovahlord** [comment]
Flight 1 = is disable gravity which effectively disables pathfinding so clipping is an expected result. In fact I highly doubt that disable gravity for that valkyr is correct so please check your sniffs again and post a packet snippet of the movement flags of the valkyr's monster move packets.

**Comment by Nyr97** [comment]
But the clipping keeps happening when Flying is set to 0 once it aligns to the target or when it finishes moving pre-aligning.

**Comment by Nyr97** [comment]
I've been testing these changes further and it seems to have fixed that clipping through the ground: when ground set to 2 and flying to 0 the creature won't clip through when aligning to the player and when moving pre-aligning.

**Pull request closed without merging**
